export const unidades = [
  {
    id: 'rj-centro',
    nome: 'Rio de Janeiro',
    bairro: 'Centro',
    estado: 'RJ',
    sigla: 'Centro, RJ',
    endereco: 'Rua da Carioca, 45 — Centro, Rio de Janeiro, RJ',
    horario: 'Seg–Sex: 07h às 20h | Sáb: 08h às 18h',
    aberta: true,
  },
  {
    id: 'sp-centro',
    nome: 'São Paulo',
    bairro: 'Centro',
    estado: 'SP',
    sigla: 'Centro, SP',
    endereco: 'Rua XV de Novembro, 120 — Centro, São Paulo, SP',
    horario: 'Seg–Sex: 07h às 21h | Sáb: 08h às 18h',
    aberta: true,
  },
  {
    id: 'pe-centro',
    nome: 'Recife',
    bairro: 'Centro',
    estado: 'PE',
    sigla: 'Centro, PE',
    endereco: 'Rua do Bom Jesus, 33 — Centro, Recife, PE',
    horario: 'Seg–Dom: 06h às 20h',
    aberta: true,
  },
  {
    id: 'pr-centro',
    nome: 'Curitiba',
    bairro: 'Centro',
    estado: 'PR',
    sigla: 'Centro, PR',
    endereco: 'Rua XV de Novembro, 87 — Centro, Curitiba, PR',
    horario: 'Seg–Sex: 08h às 19h | Sáb: 09h às 16h',
    aberta: true,
  },
  {
    id: 'sc-centro',
    nome: 'Florianópolis',
    bairro: 'Centro',
    estado: 'SC',
    sigla: 'Centro, SC',
    endereco: 'Rua Felipe Schmidt, 78 — Centro, Florianópolis, SC',
    horario: 'Seg–Sex: 08h às 19h | Sáb: 09h às 15h',
    aberta: true,
  },
]